### ISSUE TITLE
Mocking a function taking void as its only argument does not work

### ISSUE THREAD

**Issue by eerimoq** [vberlier/narmock#1]
Hello!

Mocking a function taking `void` as its only argument does not work (or explicitly no arguments really).

``` c
int func(void);

#include <narwhal/narwhal.h>

TEST(foo)
{
    MOCK(func)->disable_mock();
    func();
}

int main()
{
    return RUN_TESTS(foo);
}
```

Generate the mock.

``` text
gcc -E main.c | narmock -g mocks.c
```

The generated functions has one arguemnt, `arg1`, of the invalid type `void`.

``` c
...
// NARMOCK_IMPLEMENTATION func

int __real_func(void arg1);
...
```

**Comment by vberlier** [comment]
Thanks for the help! Just fixed it f265dbb7e23d16b28a6d0c3c9f95f4db3f257fc1 :+1:
