### ISSUE TITLE
argument names in last_call

### ISSUE THREAD

**Issue by eerimoq** [vberlier/narmock#5]
Hello,

why are the arguments called `arg1`, `arg2`, ... in `last_call` instead of the names in the function declaration?

**Comment by vberlier** [comment]
There are several reasons. The first one is that in system header files, argument names are not particularly pretty or usable. For example, this is what the declaration of `mount` in `sys/mount.h` looks like on my computer:

```c
extern int mount (const char *__special_file, const char *__dir,
		  const char *__fstype, unsigned long int __rwflag,
		  const void *__data) __THROW;
```

Not overriding the arguments would make you write code like this:

```c
MOCK(mount)->last_call->__special_file
```

Secondly, as far as I know, argument names are not guaranteed to be the same everywhere and can be vendor-specific. Even online references don't agree on a particular signature. Relying on vendor-specific argument names would make mock generation platform-dependent.

And of course, even if argument names were actually usable and standardized, it's perfectly valid C for them to be omitted in function declarations:

```c
int add(int, int);
```

**Comment by eerimoq** [comment]
I think many project would benefit from function declaration names, especially bigger projects where mostly project-internal functions are mocked.

Unrelated, I suggest documenting which platform-functions (open/close/pipe/...) Narwhal uses as mocking these could result it unwanted/unexpected behaviour.

**Comment by vberlier** [comment]
I guess this could be configurable with a command-line argument:

```bash
$ gcc -E *.c | narmock -g --keep-args
```

The process created for each test pretty much only uses write() to communicate data about the assertion and the result of the test through a pipe. I'm thinking about generating a function to reset all the mocks that would be called before reporting anything to the parent process.

**Comment by eerimoq** [comment]
Sounds good!

**Comment by vberlier** [comment]
Just closed #6. Narwhal now calls `narmock_reset_all_mocks` right before and after running user code. This should make it extremely unlikely for mocks to interfere with the framework.

**Comment by vberlier** [comment]
I think I'm going to make things a bit more flexible by letting the user specify a regular expression:

```bash
$ gcc -E *.c | narmock -g --keep-args 'myproject_.*'
```

**Comment by vberlier** [comment]
Just added a new `-k` flag that does exactly that in version 0.2.10.
