### ISSUE TITLE
mock_return_once()

### ISSUE THREAD

**Issue by eerimoq** [vberlier/narmock#7]
Hello!

In https://github.com/vberlier/narwhal/issues/3#issuecomment-506565805 an example shows future functionality, allowing the user to specify a sequence of values to return from the mock. Are there any plans on releasing that?

**Comment by vberlier** [comment]
Yeah there are still a couple of things I want to add. The problem I'm facing is that `mock_return_once()` would need to allocate memory to schedule the calls. I'm thinking about restricting the number of scheduled calls to store everything in a static array and keep the entire API allocation-free, but I'm not sure if it's a good trade-off.

When I figure this out I also want to implement something kind of based on your original proposition where you can `expect` calls:

```c
TEST(xmount_ok)
{
    MOCK(mount)
        ->mock_return_once(0)
        ->disable_mock_once()
        ->mock_return_once(42)
        ->expect("a1", "b", "c", 0, "")->expect_return(0)
        ->expect("a2", "b", "c", 0, "")->expect_return(-1)->expect_errno(ENOENT)
        ->expect("a3", "b", "c", 0, "")->expect_return(42);

    xmount("a1", "b", "c"); // return 0
    xmount("a2", "b", "c"); // return -1
    xmount("a3", "b", "c"); // return 42

    ASSERT_EQ(MOCK(mount)->call_count, 3);
}
```

**Comment by vberlier** [comment]
And there's a similar problem for storing the arguments of every call in an array, I'm not sure about making the mocked function allocate to resize the array right in the middle of user code. I'm also trying to think about a way to make it opt-in:

```c
TEST(xmount_ok)
{
    MOCK(mount)->start_watching();

    xmount("a1", "b", "c");

    MOCK(mount)->stop_watching();

    xmount("a2", "b", "c");

    MOCK(mount)->start_watching();

    xmount("a3", "b", "c");

    ASSERT_EQ(MOCK(mount)->calls[0].arg1, "a1");
    ASSERT_EQ(MOCK(mount)->calls[1].arg1, "a3");
}
```

**Comment by eerimoq** [comment]
Okay, nice.

I'm evaluating some ideas in my fork on narmock. It's a combination of narmock and cmock. It currently looks like this: https://github.com/eerimoq/narmock/blob/master/tests/main.c

**Comment by vberlier** [comment]
These `(set|ignore)_(<param>)_(in|out)` functions look pretty interesting. `assert_completed` seems useful as well, gonna make a not on that

**Comment by vberlier** [comment]
These `(set|ignore)_<arg>_(in|out)` functions look pretty interesting. The `assert_completed` function could also be useful in combination with the `expect` API I have in mind.
